// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using music_manager_starter.Server.Data;

#nullable disable

namespace music_manager_starter.Server.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20250204022529_CreatePlaylistModel")]
    partial class CreatePlaylistModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("music_manager_starter.Shared.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("music_manager_starter.Shared.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AlbumArt")
                        .HasColumnType("BLOB");

                    b.Property<string>("AlbumArtContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRatingSum")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f47c84f-4a7d-4e83-8b8f-1829f0eafca3"),
                            Album = "Spiritbox",
                            Artist = "Spiritbox",
                            Genre = "Metal",
                            RatingCount = 0,
                            Title = "Circle With Me",
                            TotalRatingSum = 0
                        },
                        new
                        {
                            Id = new Guid("2a76a0b1-b3e1-4ff0-9aa5-5f5e4c81bc45"),
                            Album = "Canyon",
                            Artist = "Pony Bradshaw",
                            Genre = "Folk",
                            RatingCount = 0,
                            Title = "Notes on a River Town",
                            TotalRatingSum = 0
                        },
                        new
                        {
                            Id = new Guid("fa38a0ed-4f00-48e2-b9c5-5d68f9c0ef41"),
                            Album = "Single",
                            Artist = "Morgan Allen",
                            Genre = "Country",
                            RatingCount = 0,
                            Title = "Flower Shops",
                            TotalRatingSum = 0
                        },
                        new
                        {
                            Id = new Guid("d94aa1d4-75ee-4f7a-a89f-f77de7050c8d"),
                            Album = "I Love You.",
                            Artist = "The Neighbourhood",
                            Genre = "Alternative",
                            RatingCount = 0,
                            Title = "Sweater Weather",
                            TotalRatingSum = 0
                        },
                        new
                        {
                            Id = new Guid("42e4b4d5-93bb-4e46-bb6e-c57de62e7f6e"),
                            Album = "When We All Fall Asleep, Where Do We Go?",
                            Artist = "Billie Eilish",
                            Genre = "Pop",
                            RatingCount = 0,
                            Title = "When the Party's Over",
                            TotalRatingSum = 0
                        },
                        new
                        {
                            Id = new Guid("b7cc1c82-77e2-40d0-8bc2-d7e05962c0e3"),
                            Album = "The Great Escape",
                            Artist = "French Cassettes",
                            Genre = "Indie",
                            RatingCount = 0,
                            Title = "Utah",
                            TotalRatingSum = 0
                        },
                        new
                        {
                            Id = new Guid("22aa6f84-06d8-4a0e-bdad-3000b35b5b5f"),
                            Album = "Twelve Carat Toothache",
                            Artist = "Post Malone",
                            Genre = "Hip Hop",
                            RatingCount = 0,
                            Title = "Something Real",
                            TotalRatingSum = 0
                        });
                });

            modelBuilder.Entity("music_manager_starter.Shared.Models.Song", b =>
                {
                    b.HasOne("music_manager_starter.Shared.Models.Playlist", null)
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId");
                });

            modelBuilder.Entity("music_manager_starter.Shared.Models.Playlist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
